services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn motionbot_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: motionbot
    databaseName: aaron-data-bank
    user: catsnaxx
