# Generated by Django 5.0.4 on 2024-04-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Motions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.CharField(max_length=200)),
                ('infoSlide', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('motionOwner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='motionbot_backend.accounts')),
            ],
        ),
    ]
