# Generated by Django 5.0.4 on 2024-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motions',
            name='motionTheme',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
