# Generated by Django 5.0.4 on 2024-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0002_motions_motiontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email_address',
            field=models.CharField(default='no email', max_length=200),
        ),
    ]
