# Generated by Django 5.0.4 on 2024-04-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0003_accounts_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='motions',
            name='motionDifficulty',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
