# Generated by Django 5.0.4 on 2024-04-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0004_motions_motiondifficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motions',
            name='motionOwner',
        ),
        migrations.AlterField(
            model_name='motions',
            name='infoSlide',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
