# Generated by Django 5.0.4 on 2024-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0005_remove_motions_motionowner_alter_motions_infoslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motions',
            name='infoSlide',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='motions',
            name='motionDifficulty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='motions',
            name='motionTheme',
            field=models.CharField(max_length=200),
        ),
    ]
