# Generated by Django 5.0.4 on 2024-04-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0007_rename_motion_motions_motionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motions',
            name='infoSlide',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
