# Generated by Django 5.0.4 on 2024-04-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0010_alter_motions_infoslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motions',
            name='motionName',
            field=models.CharField(max_length=1000),
        ),
    ]
