<<<<<<< HEAD
# Generated by Django 5.0.4 on 2025-06-24 03:27
=======
# Generated by Django 5.0.4 on 2025-05-28 03:07
>>>>>>> ca871ab16c1b105669bd67e7e26dd9084ca29bcf

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbot_backend', '0011_alter_motions_motionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
